# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on PR to the master/main branch. 
  # It is advised to work on a feature branch and not the master/main branch.
  pull_request:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job Unit-tests"
  Unit-tests:
    # Set the self hosted runner
    runs-on: self-hosted

    steps:
      # Checkout the repository to the runner
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run Test Cases
        run: |
          function Find-ViFiles {
              param (
                  [string]$path
              )

              Get-ChildItem $path -Recurse | ForEach-Object {
                  if ($_.PSIsContainer) {
                      Find-ViFiles $_.FullName
                  }
                  elseif ($_.Extension -eq ".vi") {
                      $isFileExist = $true
                      Write-Output ("`n`nFound .vi file: " + $_.FullName)
                      Write-Output ("Running unit test file " + $_.FullName)
                      g-cli --lv-ver 2020 $_.FullName
                  }
              }
          }

          # The starting directory for iteration
          $starting_directory = "Tests"


          $isFileExist = $false
          Find-ViFiles $starting_directory


          if ($isFileExist -eq $false) {
              Write-Output "No test files found"
          }

          Write-Output $isFileExist




